[2024-10-03T19:24:30.384+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_company_snapshot manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.396+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_company_snapshot manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.396+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-03T19:24:30.411+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_postgres_fmcsa_company_snapshot> on 2024-10-03 19:24:27.152457+00:00
[2024-10-03T19:24:30.418+0000] {standard_task_runner.py:57} INFO - Started process 1011 to run task
[2024-10-03T19:24:30.427+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'clever_main_DAG', 'upload_to_postgres_fmcsa_company_snapshot', 'manual__2024-10-03T19:24:27.152457+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/clever_main_DAG.py', '--cfg-path', '/tmp/tmpqum2kuc9']
[2024-10-03T19:24:30.432+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask upload_to_postgres_fmcsa_company_snapshot
[2024-10-03T19:24:30.558+0000] {task_command.py:410} INFO - Running <TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_company_snapshot manual__2024-10-03T19:24:27.152457+00:00 [running]> on host 0ed64f12ba94
[2024-10-03T19:24:30.696+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alec.ventura' AIRFLOW_CTX_DAG_ID='clever_main_DAG' AIRFLOW_CTX_TASK_ID='upload_to_postgres_fmcsa_company_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T19:24:27.152457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T19:24:27.152457+00:00'
[2024-10-03T19:24:30.699+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/clever_main_pipeline.py", line 10, in upload_to_postgres
    f'dags/scripts/data_examples/{file_name}'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'dags/scripts/data_examples/fmcsa_company_snapshot.csv'
[2024-10-03T19:24:30.706+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=clever_main_DAG, task_id=upload_to_postgres_fmcsa_company_snapshot, execution_date=20241003T192427, start_date=20241003T192430, end_date=20241003T192430
[2024-10-03T19:24:30.713+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 23 for task upload_to_postgres_fmcsa_company_snapshot ([Errno 2] No such file or directory: 'dags/scripts/data_examples/fmcsa_company_snapshot.csv'; 1011)
[2024-10-03T19:24:30.737+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-03T19:24:30.791+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
