[2024-10-03T19:24:30.281+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_safer_data manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.290+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_safer_data manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.291+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-03T19:24:30.303+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_postgres_fmcsa_safer_data> on 2024-10-03 19:24:27.152457+00:00
[2024-10-03T19:24:30.314+0000] {standard_task_runner.py:57} INFO - Started process 1007 to run task
[2024-10-03T19:24:30.332+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'clever_main_DAG', 'upload_to_postgres_fmcsa_safer_data', 'manual__2024-10-03T19:24:27.152457+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/clever_main_DAG.py', '--cfg-path', '/tmp/tmpuguvkjhh']
[2024-10-03T19:24:30.345+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask upload_to_postgres_fmcsa_safer_data
[2024-10-03T19:24:30.453+0000] {task_command.py:410} INFO - Running <TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_safer_data manual__2024-10-03T19:24:27.152457+00:00 [running]> on host 0ed64f12ba94
[2024-10-03T19:24:30.607+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alec.ventura' AIRFLOW_CTX_DAG_ID='clever_main_DAG' AIRFLOW_CTX_TASK_ID='upload_to_postgres_fmcsa_safer_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T19:24:27.152457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T19:24:27.152457+00:00'
[2024-10-03T19:24:30.612+0000] {timeout.py:68} ERROR - Process timed out, PID: 1007
[2024-10-03T19:24:30.631+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1623, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/clever_main_pipeline.py", line 10, in upload_to_postgres
    f'dags/scripts/data_examples/{file_name}'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'dags/scripts/data_examples/fmcsa_safer_data.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 1007
[2024-10-03T19:24:30.642+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=clever_main_DAG, task_id=upload_to_postgres_fmcsa_safer_data, execution_date=20241003T192427, start_date=20241003T192430, end_date=20241003T192430
[2024-10-03T19:24:30.669+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task upload_to_postgres_fmcsa_safer_data (Timeout, PID: 1007; 1007)
[2024-10-03T19:24:30.716+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-03T19:24:30.737+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
