[2024-10-03T19:24:30.296+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_companies manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.303+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_companies manual__2024-10-03T19:24:27.152457+00:00 [queued]>
[2024-10-03T19:24:30.303+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-03T19:24:30.317+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_postgres_fmcsa_companies> on 2024-10-03 19:24:27.152457+00:00
[2024-10-03T19:24:30.329+0000] {standard_task_runner.py:57} INFO - Started process 1009 to run task
[2024-10-03T19:24:30.338+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'clever_main_DAG', 'upload_to_postgres_fmcsa_companies', 'manual__2024-10-03T19:24:27.152457+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/clever_main_DAG.py', '--cfg-path', '/tmp/tmpojdb6g4u']
[2024-10-03T19:24:30.347+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask upload_to_postgres_fmcsa_companies
[2024-10-03T19:24:30.454+0000] {task_command.py:410} INFO - Running <TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_companies manual__2024-10-03T19:24:27.152457+00:00 [running]> on host 0ed64f12ba94
[2024-10-03T19:24:30.615+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alec.ventura' AIRFLOW_CTX_DAG_ID='clever_main_DAG' AIRFLOW_CTX_TASK_ID='upload_to_postgres_fmcsa_companies' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T19:24:27.152457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T19:24:27.152457+00:00'
[2024-10-03T19:24:30.624+0000] {timeout.py:68} ERROR - Process timed out, PID: 1009
[2024-10-03T19:24:30.634+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1623, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/clever_main_pipeline.py", line 10, in upload_to_postgres
    f'dags/scripts/data_examples/{file_name}'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'dags/scripts/data_examples/fmcsa_companies.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 1009
[2024-10-03T19:24:30.646+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=clever_main_DAG, task_id=upload_to_postgres_fmcsa_companies, execution_date=20241003T192427, start_date=20241003T192430, end_date=20241003T192430
[2024-10-03T19:24:30.689+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 21 for task upload_to_postgres_fmcsa_companies (Timeout, PID: 1009; 1009)
[2024-10-03T19:24:30.726+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-03T19:24:30.762+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
